package com.pgamotors.survivorship.physicalPerson.test_amf 

KnowledgeBuilderConfiguration kbConfig = KnowledgeBuilderFactory.newKnowledgeBuilderConfiguration();

kbConfig.setProperty("drools.dialect.mvel.strict", "false");

KnowledgeBuilder kBuilder = KnowledgeBuilderFactory.newKnowledgeBuilder( kbConfig );
rule "1_Firstname"
    no-loop true
    dialect "mvel"
    ruleflow-group "1_FirstnameGroup"
when
    $input : RecordIn( dataset.isLatest( firstname_norm, "firstname_norm" ) )  
then
    dataset.survive( $input.TALEND_INTERNAL_ID, "firstname_norm" );

end


